### ISSUE TITLE
Add the config option to CasModule for which URLs to protect with CAS

### ISSUE THREAD

**Issue by dima767** [UniconLabs/ratpack-modules#1]
Something like:

``` groovy
new CasModule(hostPort: 'http://localhost:5050',
                            casUrl:'https://test.scaldingspoon.org/cas', 
                            protectedEndpoints:['/hello', '/bye'])
```

... and implementation of course :-)

**Comment by scalding** [comment]
So, right now, as a module it asserts itself at the start of the handler chain, so it protects everything. What I've thought of doing is just supplying the handler so you can add it to whatever chain you want, which might make more sense than yet another configuration option :)

**Comment by dima767** [comment]
Perhaps. How would it look like?

**Comment by scalding** [comment]
Okay, version > 0.0.4 has a little bit of separation between the handler and the module, which will allow you to configure the handler separately. In the `ratpack-sample` subproject, I've set up a handler chain for the `hello` path seen [here](https://github.com/UniconLabs/ratpack-modules/blob/05ddf88a57c186465438d349416b0ae25c51ac67/ratpack-sample/src/ratpack/ratpack.groovy#L15). First it adds the [casHandler](https://github.com/UniconLabs/ratpack-modules/blob/05ddf88a57c186465438d349416b0ae25c51ac67/ratpack-sample/src/ratpack/ratpack.groovy#L8) then adds a simple closure handler that just sends a response. Clear as mud? ;)

**Comment by scalding** [comment]
By the way, you should be able to check out the repo and run `./gradlew :ratpack-sample:run` to check it out. I'll try to keep the sample up to date with usage (but probably not gradle config, since it's all in the same project)

**Comment by scalding** [comment]
one more bit :) you can also use a prefix to set up a chain as well. I'll set up some samples for that sometime later

**Comment by dima767** [comment]
Looks good. I'll try it tomorrow

—

**Comment by dima767** [comment]
Is this still being maintained? Closing...
